/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Text;
export const SaveStateId = IDL.Text;
export const EntryMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Null = IDL.Null;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GameSaveState = IDL.Record({
  'metadata' : EntryMetadata,
  'binaryData' : IDL.Vec(IDL.Nat8),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func(
      [GameId, SaveStateId, EntryMetadata, IDL.Vec(IDL.Nat8)],
      [Null],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSaveForGame' : IDL.Func([GameId, SaveStateId], [Null], []),
  'getAllEntriesByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(EntryMetadata)],
      ['query'],
    ),
  'getAllSavesForGame' : IDL.Func(
      [GameId],
      [IDL.Vec(EntryMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestSaveForGame' : IDL.Func(
      [GameId],
      [IDL.Opt(GameSaveState)],
      ['query'],
    ),
  'getSaveForGame' : IDL.Func(
      [GameId, SaveStateId],
      [IDL.Opt(GameSaveState)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Text;
  const SaveStateId = IDL.Text;
  const EntryMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Null = IDL.Null;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GameSaveState = IDL.Record({
    'metadata' : EntryMetadata,
    'binaryData' : IDL.Vec(IDL.Nat8),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func(
        [GameId, SaveStateId, EntryMetadata, IDL.Vec(IDL.Nat8)],
        [Null],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSaveForGame' : IDL.Func([GameId, SaveStateId], [Null], []),
    'getAllEntriesByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(EntryMetadata)],
        ['query'],
      ),
    'getAllSavesForGame' : IDL.Func(
        [GameId],
        [IDL.Vec(EntryMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestSaveForGame' : IDL.Func(
        [GameId],
        [IDL.Opt(GameSaveState)],
        ['query'],
      ),
    'getSaveForGame' : IDL.Func(
        [GameId, SaveStateId],
        [IDL.Opt(GameSaveState)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };