/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EntryMetadata {
  'id' : string,
  'title' : string,
  'description' : string,
  'timestamp' : bigint,
}
export type GameId = string;
export interface GameSaveState {
  'metadata' : EntryMetadata,
  'binaryData' : Uint8Array,
}
export type Null = null;
export type SaveStateId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntry' : ActorMethod<
    [GameId, SaveStateId, EntryMetadata, Uint8Array],
    Null
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSaveForGame' : ActorMethod<[GameId, SaveStateId], Null>,
  'getAllEntriesByTimestamp' : ActorMethod<[], Array<EntryMetadata>>,
  'getAllSavesForGame' : ActorMethod<[GameId], Array<EntryMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestSaveForGame' : ActorMethod<[GameId], [] | [GameSaveState]>,
  'getSaveForGame' : ActorMethod<[GameId, SaveStateId], [] | [GameSaveState]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];